In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd


model = LinearRegression()
model.fit(X_train_scaled, y_train)


y_pred = model.predict(X_test_scaled)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Linear Regression Model eka train karala iwarai!\n")
print("Mean Squared Error (MSE):", mse)
print("R-squared:", r2)


column_names_features = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']
coefficients = pd.DataFrame({'Feature': column_names_features, 'Coefficient': model.coef_})
print("\nModel Coefficients:\n", coefficients)

Linear Regression Model eka train karala iwarai!

Mean Squared Error (MSE): 24.291119474973513
R-squared: 0.668759493535632

Model Coefficients:
     Feature  Coefficient
0      CRIM    -1.002135
1        ZN     0.696269
2     INDUS     0.278065
3      CHAS     0.718738
4       NOX    -2.022319
5        RM     3.145240
6       AGE    -0.176048
7       DIS    -3.081908
8       RAD     2.251407
9       TAX    -1.767014
10  PTRATIO    -2.037752
11        B     1.129568
12    LSTAT    -3.611658

In [14]:

df.head()

  0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'Price']
df = pd.read_csv('/4) house Prediction Data Set.csv', delim_whitespace=True, names=column_names)


X = df.drop('Price', axis=1)
y = df['Price']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data has been correctly separated and scaled successfully!")
print("(Train size):", X_train_scaled.shape)
print("(Test size):", X_test_scaled.shape)

Data has been correctly separated and scaled successfully!
(Train size): (404, 13)
(Test size): (102, 13)

/tmp/ipykernel_3831/2949511391.py:7: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('/4) house Prediction Data Set.csv', delim_whitespace=True, names=column_names)

In [12]:

df = df.drop('ADDRESS', axis=1)


df = pd.get_dummies(df, drop_first=True)


df.head()

KeyError: "['ADDRESS'] not found in axis"

In [5]:

print(df.isnull().sum())

0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00    0
dtype: int64

In [13]:
import pandas as pd


df = pd.read_csv('/4) house Prediction Data Set.csv')


df.head()

  0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...